language: java

jdk:
  - openjdk8

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - build/libs

stages:
  - test
  - build
  - deploy

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

before_install:
  - chmod +x ./gradlew

before_deploy:
  - yarn add heroku heroku-cli-deploy
  - heroku plugins:install heroku-cli-deploy

after_deploy:
  - rm -rf build/libs/

jobs:
  include:
  - stage: test
    name: Tests
    script: ./gradlew test
  - stage: build
    name: Build Pressurizer
    script: ./gradlew shadowJar
  - stage: deploy
    name: Deploy to Heroku
    install: skip
    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script: heroku deploy:jar build/libs/pressurizer.jar --app pressurizer
      on:
        branch: master