dist: xenial
sudo: true
language: java
jdk: openjdk8

services: postgresql

addons:
  postgresql: "10"

env:
  global:
    - PGHOST=localhost
    - PGPORT=5432

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - build/libs

stages:
  - name: build
  - name: test
  - name: fatJar
    if: branch IN (master, develop)
  - name: deploy
    if: branch = master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

before_deploy:
  - yarn add heroku heroku-cli-deploy
  - heroku plugins:install heroku-cli-deploy

after_deploy:
  - rm -rf build/libs/

jobs:
  include:
    - stage: build
      name: Build Pressurizer
      install: skip
      script: ./gradlew --no-daemon compileKotlin

    - stage: test
      name: Tests
      install: skip
      before_script:
        - psql -c "CREATE DATABASE pressurizer_test;" -U postgres
        - psql -c "CREATE USER pressurizer_test WITH PASSWORD 'pressurizer_test';" -U postgres
        - psql -c "GRANT ALL PRIVILEGES ON DATABASE pressurizer_test TO pressurizer_test;" -U postgres
      script: ./gradlew --no-daemon test
      after_success:
        - ./gradlew --no-daemon uploadReportCodacy
        - bash <(curl -s https://codecov.io/bash)

    - stage: fatJar
      name: Create fat JAR Pressurizer
      install: skip
      script: ./gradlew --no-daemon shadowJar

    - stage: deploy
      name: Deploy to Heroku
      install: skip
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: heroku deploy:jar build/libs/pressurizer.jar --app pressurizer