INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('AED', 'DH', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('ARS', 'ARS$', '.', ',');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('AUD', 'A$', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('BRL', 'R$', '.', ',');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('CAD', 'CDN$', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('CHF', 'CHF', NULL, '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('CLP', 'CLP$', '.', ',');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('CNY', '¥', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('COP', 'COL$', '.', ',');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('CRC', '₡', '.', ',');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('EUR', '€', NULL, ',');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('GBP', '£', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('HKD', 'HK$', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('IDR', 'Rp', ' ', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('ILS', '₪', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('INR', '₹', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('JPY', '¥', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('KRW', '₩', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('KWD', 'KD', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('KZT', '₸', NULL, '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('MXN', 'Mex$', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('MYR', 'RM', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('NOK', 'kr', '.', ',');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('NZD', 'NZ$', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('PEN', 'S/.', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('PHP', 'P', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('PLN', 'zł', NULL, ',');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('QAR', 'QR', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('RUB', 'pуб.', NULL, ',');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('SAR', 'SR', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('SGD', 'S$', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('THB', '฿', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('TRY', 'TL', NULL, ',');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('TWD', 'NT$', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('UAH', '₴', NULL, ',');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('USD', '$', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('UYU', '$U', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('VND', '₫', ',', '.');
INSERT INTO public.currencies (currency_code, currency_symbol, thousand_separator, decimal_separator) VALUES ('ZAR', 'R', NULL, '.');

INSERT INTO public.countries (country_code, country_name, currency) VALUES ('AD', 'Andorra', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('AE', 'United Arab Emirates', 'AED');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('AF', 'Afghanistan', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('AG', 'Antigua and Barbuda', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('AI', 'Anguilla', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('AL', 'Albania', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('AM', 'Armenia', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('AO', 'Angola', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('AQ', 'Antarctica', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('AR', 'Argentina', 'ARS');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('AS', 'American Samoa', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('AT', 'Austria', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('AU', 'Australia', 'AUD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('AW', 'Aruba', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('AX', 'Åland Islands', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('AZ', 'Azerbaijan', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('BA', 'Bosnia and Herzegovina', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('BB', 'Barbados', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('BD', 'Bangladesh', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('BE', 'Belgium', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('BF', 'Burkina Faso', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('BG', 'Bulgaria', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('BH', 'Bahrain', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('BI', 'Burundi', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('BJ', 'Benin', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('BL', 'Saint Barthélemy', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('BM', 'Bermuda', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('BN', 'Brunei Darussalam', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('BO', 'Bolivia, Plurinational State of', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('BQ', 'Bonaire, Sint Eustatius and Saba', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('BR', 'Brazil', 'BRL');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('BS', 'Bahamas', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('BT', 'Bhutan', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('BV', 'Bouvet Island', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('BW', 'Botswana', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('BY', 'Belarus', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('BZ', 'Belize', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('CA', 'Canada', 'CAD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('CC', 'Cocos (Keeling) Islands', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('CD', 'Congo, the Democratic Republic of the', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('CF', 'Central African Republic', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('CG', 'Congo', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('CH', 'Switzerland', 'CHF');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('CI', 'Côte d''Ivoire', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('CK', 'Cook Islands', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('CL', 'Chile', 'CLP');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('CM', 'Cameroon', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('CN', 'China', 'CNY');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('CO', 'Colombia', 'COP');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('CR', 'Costa Rica', 'CRC');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('CU', 'Cuba', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('CV', 'Cape Verde', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('CW', 'Curaçao', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('CX', 'Christmas Island', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('CY', 'Cyprus', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('CZ', 'Czech Republic', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('DE', 'Germany', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('DJ', 'Djibouti', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('DK', 'Denmark', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('DM', 'Dominica', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('DO', 'Dominican Republic', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('DZ', 'Algeria', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('EC', 'Ecuador', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('EE', 'Estonia', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('EG', 'Egypt', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('EH', 'Western Sahara', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('ER', 'Eritrea', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('ES', 'Spain', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('ET', 'Ethiopia', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('FI', 'Finland', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('FJ', 'Fiji', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('FK', 'Falkland Islands (Malvinas)', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('FM', 'Micronesia, Federated States of', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('FO', 'Faroe Islands', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('FR', 'France', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('GA', 'Gabon', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('GB', 'United Kingdom', 'GBP');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('GD', 'Grenada', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('GE', 'Georgia', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('GF', 'French Guiana', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('GG', 'Guernsey', 'GBP');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('GH', 'Ghana', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('GI', 'Gibraltar', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('GL', 'Greenland', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('GM', 'Gambia', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('GN', 'Guinea', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('GP', 'Guadeloupe', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('GQ', 'Equatorial Guinea', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('GR', 'Greece', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('GS', 'South Georgia and the South Sandwich Islands', 'GBP');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('GT', 'Guatemala', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('GU', 'Guam', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('GW', 'Guinea-Bissau', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('GY', 'Guyana', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('HK', 'Hong Kong', 'HKD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('HM', 'Heard Island and McDonald Islands', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('HN', 'Honduras', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('HR', 'Croatia', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('HT', 'Haiti', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('HU', 'Hungary', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('ID', 'Indonesia', 'IDR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('IE', 'Ireland', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('IL', 'Israel', 'ILS');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('IM', 'Isle of Man', 'GBP');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('IN', 'India', 'INR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('IO', 'British Indian Ocean Territory', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('IQ', 'Iraq', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('IR', 'Iran, Islamic Republic of', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('IS', 'Iceland', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('IT', 'Italy', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('JE', 'Jersey', 'GBP');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('JM', 'Jamaica', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('JO', 'Jordan', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('JP', 'Japan', 'JPY');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('KE', 'Kenya', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('KG', 'Kyrgyzstan', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('KH', 'Cambodia', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('KI', 'Kiribati', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('KM', 'Comoros', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('KN', 'Saint Kitts and Nevis', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('KP', 'Korea, Democratic People''s Republic of', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('KR', 'Korea, Republic of', 'KRW');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('KW', 'Kuwait', 'KWD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('KY', 'Cayman Islands', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('KZ', 'Kazakhstan', 'KZT');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('LA', 'Lao People''s Democratic Republic', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('LB', 'Lebanon', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('LC', 'Saint Lucia', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('LI', 'Liechtenstein', 'CHF');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('LK', 'Sri Lanka', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('LR', 'Liberia', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('LS', 'Lesotho', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('LT', 'Lithuania', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('LU', 'Luxembourg', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('LV', 'Latvia', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('LY', 'Libya', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('MA', 'Morocco', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('MC', 'Monaco', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('MD', 'Moldova, Republic of', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('ME', 'Montenegro', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('MF', 'Saint Martin (French part)', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('MG', 'Madagascar', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('MH', 'Marshall Islands', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('MK', 'Macedonia, the Former Yugoslav Republic of', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('ML', 'Mali', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('MM', 'Myanmar', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('MN', 'Mongolia', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('MO', 'Macao', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('MP', 'Northern Mariana Islands', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('MQ', 'Martinique', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('MR', 'Mauritania', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('MS', 'Montserrat', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('MT', 'Malta', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('MU', 'Mauritius', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('MV', 'Maldives', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('MW', 'Malawi', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('MX', 'Mexico', 'MXN');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('MY', 'Malaysia', 'MYR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('MZ', 'Mozambique', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('NA', 'Namibia', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('NC', 'New Caledonia', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('NE', 'Niger', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('NF', 'Norfolk Island', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('NG', 'Nigeria', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('NI', 'Nicaragua', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('NL', 'Netherlands', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('NO', 'Norway', 'NOK');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('NP', 'Nepal', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('NR', 'Nauru', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('NU', 'Niue', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('NZ', 'New Zealand', 'NZD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('OM', 'Oman', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('PA', 'Panama', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('PE', 'Peru', 'PEN');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('PF', 'French Polynesia', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('PG', 'Papua New Guinea', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('PH', 'Philippines', 'PHP');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('PK', 'Pakistan', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('PL', 'Poland', 'PLN');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('PM', 'Saint Pierre and Miquelon', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('PN', 'Pitcairn', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('PR', 'Puerto Rico', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('PS', 'Palestine, State of', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('PT', 'Portugal', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('PW', 'Palau', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('PY', 'Paraguay', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('QA', 'Qatar', 'QAR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('RE', 'Réunion', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('RO', 'Romania', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('RS', 'Serbia', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('RU', 'Russian Federation', 'RUB');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('RW', 'Rwanda', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('SA', 'Saudi Arabia', 'SAR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('SB', 'Solomon Islands', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('SC', 'Seychelles', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('SD', 'Sudan', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('SE', 'Sweden', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('SG', 'Singapore', 'SGD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('SI', 'Slovenia', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('SJ', 'Svalbard and Jan Mayen', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('SK', 'Slovakia', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('SL', 'Sierra Leone', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('SM', 'San Marino', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('SN', 'Senegal', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('SO', 'Somalia', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('SR', 'Suriname', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('SS', 'South Sudan', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('ST', 'Sao Tome and Principe', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('SV', 'El Salvador', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('SX', 'Sint Maarten (Dutch part)', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('SY', 'Syrian Arab Republic', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('SZ', 'Swaziland', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('TC', 'Turks and Caicos Islands', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('TD', 'Chad', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('TF', 'French Southern Territories', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('TG', 'Togo', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('TH', 'Thailand', 'THB');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('TJ', 'Tajikistan', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('TK', 'Tokelau', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('TL', 'Timor-Leste', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('TM', 'Turkmenistan', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('TN', 'Tunisia', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('TO', 'Tonga', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('TR', 'Turkey', 'TRY');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('TT', 'Trinidad and Tobago', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('TV', 'Tuvalu', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('TW', 'Taiwan, Province of China', 'TWD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('TZ', 'Tanzania, United Republic of', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('UA', 'Ukraine', 'UAH');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('UG', 'Uganda', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('UM', 'United States Minor Outlying Islands', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('US', 'United States', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('UY', 'Uruguay', 'UYU');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('UZ', 'Uzbekistan', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('VA', 'Holy See (Vatican City State)', 'EUR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('VC', 'Saint Vincent and the Grenadines', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('VE', 'Venezuela, Bolivarian Republic of', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('VG', 'Virgin Islands, British', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('VI', 'Virgin Islands, U.S.', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('VN', 'Viet Nam', 'VND');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('VU', 'Vanuatu', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('WF', 'Wallis and Futuna', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('WS', 'Samoa', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('YE', 'Yemen', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('YT', 'Mayotte', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('ZA', 'South Africa', 'ZAR');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('ZM', 'Zambia', 'USD');
INSERT INTO public.countries (country_code, country_name, currency) VALUES ('ZW', 'Zimbabwe', 'USD');

UPDATE public.version set current_version = 1 where current_version = 0;