package me.alvr.pressurizer.utils

import me.alvr.pressurizer.domain.ShopName

val shopsName = listOf(
    ShopName("game2", "2game"),
    ShopName("allyouplay", "AllYouPlay"),
    ShopName("amazonus", "Amazon"),
    ShopName("bistore", "BI Store"),
    ShopName("battlenet", "Blizzard"),
    ShopName("chrono", "Chrono.gg"),
    ShopName("dlgamer", "DLGamer"),
    ShopName("direct2drive", "Direct2Drive"),
    ShopName("discord", "Discord Store"),
    ShopName("dreamgame", "Dreamgame"),
    ShopName("epic", "Epic Game Store"),
    ShopName("bundlestars", "Fanatical"),
    ShopName("fireflower", "FireFlower"),
    ShopName("gog", "GOG"),
    ShopName("gamejolt", "Game Jolt"),
    ShopName("gamebillet", "GameBillet"),
    ShopName("impulse", "GameStop PC"),
    ShopName("gamersgate", "GamersGate"),
    ShopName("gamesplanetde", "GamesPlanet DE"),
    ShopName("gamesplanetfr", "GamesPlanet FR"),
    ShopName("gamesplanet", "GamesPlanet UK"),
    ShopName("gamesplanetus", "GamesPlanet US"),
    ShopName("gamesrepublic", "GamesRepublic"),
    ShopName("gemly", "Gemly"),
    ShopName("greenmangaming", "GreenManGaming"),
    ShopName("humblestore", "Humble Store"),
    ShopName("humblewidgets", "Humble Widgets"),
    ShopName("indiegalastore", "IndieGala Store"),
    ShopName("itchio", "Itch.io"),
    ShopName("lbostore", "LBOstore"),
    ShopName("macgamestore", "MacGameStore"),
    ShopName("microsoft", "Microsoft Store"),
    ShopName("newegg", "Newegg"),
    ShopName("nuuvem", "Nuuvem"),
    ShopName("oculus", "Oculus Store"),
    ShopName("origin", "Origin"),
    ShopName("playism", "Playism"),
    ShopName("razer", "Razer Game Store"),
    ShopName("savemi", "Savemi"),
    ShopName("silagames", "SilaGames"),
    ShopName("squenix", "Square Enix"),
    ShopName("steam", "Steam"),
    ShopName("uplay", "Uplay"),
    ShopName("voidu", "Voidu"),
    ShopName("wingamestore", "WinGameStore")
)